/**
 * Legacy script disabled — static section sitemaps under public/ are removed.
 *
 * The only crawler sitemap is generated by Next from `app/sitemap.ts` at build time:
 *   npm run build  →  out/sitemap.xml
 *
 * Do not re-add public/sitemap*.xml or public/sitemaps/; they duplicate and confuse GSC.
 */

console.log(
  "Sitemap is built by Next.js from app/sitemap.ts. Run: npm run build (see out/sitemap.xml)"
);
process.exit(0);
